---
# tasks file for osx-r
- name: update homebrew
  homebrew: update_homebrew=yes

- name: install libssh2
  homebrew: name=libssh2 state=latest

- name: link libssh2
  homebrew: name=libssh2 state=linked

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions

- name: install r from cask
  homebrew_cask: name=r state=present

- name: install rstudio
  homebrew_cask: name={{ rstudio_cask_name }}

- name: check git2r ssh
  shell: Rscript -e 'git2r::libgit2_features()$ssh || stop()'
  register: git2r_ssh
  ignore_errors: yes

- name: install git2r from source
  command: Rscript -e 'install.packages("git2r", type="source", repos="https://cran.rstudio.com")'
  when: "{{ git2r_ssh | failed }}"

- name: install additional casks
  homebrew_cask: name={{ item }}
  with_items:
  - xquartz

- set_fact:
    ssh_key_path: "{{ ssh_keyfile | default( '~/.ssh/id_rsa' | expanduser ) }}"

- stat: path={{ ssh_key_path }}
  register: sshkeystat

- name: generate new ssh key
  command: ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
  register: newkeycmd
  when: not sshkeystat.stat.exists

- name: check if ssh key encrypted
  command: grep ENCRYPTED {{ ssh_key_path }}
  register: ssh_has_passphrase
  ignore_errors: yes

- debug: msg="Not running ssh-add; existing key is encrypted."
  when: "{{ ssh_has_passphrase | succeeded }}"

- name: run ssh-add
  command: ssh-add {{ ssh_key_path }}
  when: "{{ ssh_has_passphrase | failed }}"

